# Generated by Django 2.1.1 on 2018-09-06 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readnum',
            old_name='blog',
            new_name='content_type',
        ),
    ]
