# Generated by Django 2.1.1 on 2018-09-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_blog_reader_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='last_update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
